language: java

dist: trusty
jdk:
  - oraclejdk9
addons:
  apt:
    packages:
    - junit4
    - libmockito-java
script:
  - make -C PriorityQueue clean
  - make -C PriorityQueue compileTest
  - make -C PriorityQueue run
